//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Users = new HashSet<User>();
        }
    
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
