//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryLog
    {
        public string LogId { get; set; }
        public string LogContent { get; set; }
        public System.DateTime DateLog { get; set; }
        public string UserLog { get; set; }
    }
}
