//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodDetail
    {
        public string PeriodDetailId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> AmountDate { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<System.DateTime> AdvanceDate { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Note { get; set; }
        public string ProjectId { get; set; }
    }
}
