//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public string PermissionId { get; set; }
        public string ProjectId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
