//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public string ProfileId { get; set; }
        public string ProfileName { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string ProjectId { get; set; }
        public string PathFile { get; set; }
    }
}
