//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public string Agency { get; set; }
        public Nullable<decimal> FundsFor { get; set; }
        public Nullable<int> MonthFrom { get; set; }
        public Nullable<int> MonthTo { get; set; }
        public Nullable<int> YearFrom { get; set; }
        public Nullable<int> YearTo { get; set; }
        public Nullable<int> PlanYear { get; set; }
        public string ProjectContent { get; set; }
        public string Target { get; set; }
        public string Necessary { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<bool> Lock { get; set; }
        public string UserMain { get; set; }
        public string Note { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Degree { get; set; }
        public string AcademicTitles { get; set; }
        public string Position { get; set; }
        public string PhoneNumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string UsersJoin { get; set; }
        public string EconomyTarget { get; set; }
        public string Slogan { get; set; }
        public string Size { get; set; }
        public string ApproveNumber { get; set; }
        public string ContractNumber { get; set; }
        public string TargetExpected { get; set; }
        public string ContentExpected { get; set; }
        public string ProductExpected { get; set; }
        public Nullable<decimal> FundsForExpected { get; set; }
        public string ProjectNameExpected { get; set; }
        public string UserCreateId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserUpdateId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DepartmentId { get; set; }
        public string CareerId { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
