//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Business.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public string ScheduleId { get; set; }
        public string ScheduleName { get; set; }
        public string Content { get; set; }
        public Nullable<int> MonthFrom { get; set; }
        public Nullable<int> YearFrom { get; set; }
        public Nullable<int> MonthTo { get; set; }
        public Nullable<int> YearTo { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string Note { get; set; }
        public string ProjectId { get; set; }
    }
}
